config/routes.rb
Rails.application.routes.draw do
  get 'home_page/show'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :games do
    member do 
      patch :start
      post :guess
    end
  end
  

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root to: 'home_page#show'
end

app/models/game.rb
require_dependency './lib/games_utils'
class Game < ApplicationRecord
  include ActionView::RecordIdentifier
  include ActionView::Helpers
  include Clearance::Authentication

  has_many :game_players
  has_many :users, through: :game_players
  has_many :rounds
  
  after_create_commit { broadcast_prepend_to 'games' }
  after_destroy_commit { broadcast_remove_to 'games' }
  after_commit :change_game_status, on: :update

  default_scope { order(created_at: :desc) }

  def next_player(current_player)
    current_game_player = self.game_players.where(user_id: current_player.id).first
    next_player_order = current_game_player.player_order + 1
    next_game_player = self.game_players.where(player_order: next_player_order).first || self.game_players.first
    return User.find(next_game_player.user_id)
  end

  def change_game_status
    if self.saved_change_to_started? and self.started?
      update_game_room(:started)
    end
  end

  def update_game_room(attribute)
    current_round = Round.find(self.current_round_id)
    current_player = User.find(current_round.current_player_id)
    starting_players_money = current_round.round_players.map{ |round_player| "#{ GamesController.helpers.get_username(User.find(round_player.user_id).email)}: #{ round_player.player_money }" }
    broadcast_replace_to  [self, attribute], 
                          target: "#{dom_id(self)}_room_chooser", 
                          partial: "games/room_chooser", 
                          locals: { 
                            game: self, 
                            disk_content: GamesUtils.get_disk_content,
                            sentence: current_round.sentence, 
                            round: current_round,
                            player: current_player,
                            topic: current_round.topic,
                            opened_letters: current_round.opened_letters,
                            players_money: starting_players_money,
                          }
  broadcast_replace_later_to  [self, attribute], 
                          target: "#{dom_id(self)}_room_chooser", 
                          partial: "games/room_chooser", 
                          locals: { 
                            game: self, 
                            disk_content: GamesUtils.get_disk_content,
                            sentence: current_round.sentence, 
                            round: current_round,
                            player: current_player,
                            topic: current_round.topic,
                            opened_letters: current_round.opened_letters,
                            players_money: starting_players_money,
                          }
  end
end

app/controllers/games_controller.rb
require_dependency './lib/games_utils'
require 'tts'

class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy start guess]
  before_action :set_game_room, only: [:show, :update, :guess]
  before_action :set_waiting_room, only: [:show, :update]
  before_action :require_login
  skip_before_action :verify_authenticity_token
  include ActionView::RecordIdentifier
  include ActionView::Helpers::NumberHelper

  # GET /games or /games.json
  def index
    @games = Game.all
    @game = Game.new
  end

  # GET /games/1 or /games/1.json
  def show
    # TODO: Update to include:
    # - Rounds
    # - Players
    # - Turns
    # - Track money
    @disk_content = GamesUtils.get_disk_content
    if @round.present? and @round.over?
      next_round = @round.next
      
      if next_round.present?
        @game.update(current_round_id: next_round.id)
        update_game_room
        @current_user = current_user
        Turbo::StreamsChannel.broadcast_replace_to(
          [@game, :started], 
          target: "#{dom_id(@game)}_room_chooser", 
          partial: "games/room_chooser", 
          locals: {
            game: @game, 
            sentence: @sentence, 
            round: @round,
            player: @player,
            topic: @topic,
            opened_letters: @opened_letters,
            players_money: @players_money,
          }
        )
      else
        redirect_to games_url
      end
    # elsif @guess.present?
    #   if @sentence.include? @guess and not @opened_letters.include? @guess
    #     @round_player.update(player_money: @round_player.player_money + @sentence.count(@guess))
    #     @round.update(opened_letters: @opened_letters << @guess)  
    #   else
    #     next_player = @game.next_player(@player)
    #     @round.update(current_player_id: next_player.id)
    #   end

    #   if @sentence.chars.uniq.sort == @round.opened_letters.sort
    #     @round.update(over: true)
    #   end
    #   update_game_room  
    #   Turbo::StreamsChannel.broadcast_replace_to(
    #     [@game, :started], 
    #     target: "#{dom_id(@game)}_room_chooser", 
    #     partial: "games/room_chooser", 
    #     locals: {
    #       game: @game, 
    #       guess: @guess,
    #       sentence: @sentence, 
    #       round: @round,
    #       player: @player,
    #       topic: @topic,
    #       opened_letters: @opened_letters,
    #       players_money: @players_money,
    #       current_user_id: current_user.id
    #     }
    #   )
    end
  end

  # POST /games/1/guess
  def guess
    if current_user.id != @player.id
      redirect_to @game, alert: "It's not your turn yet!"
    else
      if @full_guess.present?
        "#{@full_guess}".play('ar')
        if @sentence == @full_guess
          'جوابْ صحيحْ'.play('ar')
          @round_player.update(player_money: @round_player.player_money + 1000)
          @round.update(opened_letters: (@opened_letters + @full_guess.gsub(/\s+/, "").split("")).uniq)  
          update_game_room  
          Turbo::StreamsChannel.broadcast_replace_to(
            [@game, :started], 
            target: "#{dom_id(@game)}_room_chooser", 
            partial: "games/room_chooser", 
            locals: {
              game: @game, 
              guess: @guess,
              sentence: @sentence, 
              round: @round,
              player: @player,
              topic: @topic,
              opened_letters: @opened_letters,
              players_money: @players_money,
            }
          )
          "مبروكْ الفْوْزْ يا  #{helpers.get_username(User.find(@round_player.user_id).email)}".play('ar')
          "رَصْيْدَكْ الْكْامِلْ هْوَ #{@round_player.player_money} دولارْ".play('ar')
        else
          'جوابْ غلطْ بغلطْ'.play('ar')
          next_player = @game.next_player(@player)
          @round.update(current_player_id: next_player.id)
          "صارْ دْوْرْ #{helpers.get_username(next_player.email)}".play('ar')
        end
      else
        if @spin_result == -1
          @round_player.update(player_money: 0)
          'راحْ الرصيدْ معَ الأسفْ'.play('ar')
          next_player = @game.next_player(@player)
          "صارْ دْوْرْ #{helpers.get_username(next_player.email)}".play('ar')
          @round.update(current_player_id: next_player.id)
        elsif @sentence.include? @guess and not @opened_letters.include? @guess
          "#{@spin_result} دولارْ".play('ar')
          "حرفُ الْ #{@guess} ".play('ar')
          'جوابْ صحيحْ'.play('ar')
          @round.update(opened_letters: @opened_letters << @guess)
          update_game_room  
          Turbo::StreamsChannel.broadcast_replace_to(
            [@game, :started], 
            target: "#{dom_id(@game)}_room_chooser", 
            partial: "games/room_chooser", 
            locals: {
              game: @game, 
              guess: @guess,
              sentence: @sentence, 
              round: @round,
              player: @player,
              topic: @topic,
              opened_letters: @opened_letters,
              players_money: @players_money,
            }
          )
          Turbo::StreamsChannel.broadcast_replace_later_to(
            [@game, :started], 
            target: "#{dom_id(@game)}_room_chooser", 
            partial: "games/room_chooser", 
            locals: {
              game: @game, 
              guess: @guess,
              sentence: @sentence, 
              round: @round,
              player: @player,
              topic: @topic,
              opened_letters: @opened_letters,
              players_money: @players_money,
            }
          )
          "موجود منهُ #{@sentence.count(@guess)}".play('ar')
          @round_player.update(player_money: @round_player.player_money + (@sentence.count(@guess) * @spin_result))
          "رَصْيْدَكْ الْكْامِلْ هْوَ #{@round_player.player_money} دولارْ".play('ar')
        else
          "#{@spin_result} دولارْ".play('ar')
          "حرفْ ال #{@guess} ".play('ar')
          'جوابْ غلطْ '.play('ar')
          next_player = @game.next_player(@player)
          @round.update(current_player_id: next_player.id)
          "صارْ دْوْرْ #{helpers.get_username(next_player.email)}".play('ar')
        end
      end

      if @sentence.chars.uniq.sort.length == @round.opened_letters.sort.length
        @round.update(over: true)
        "مبروكْ الفْوْزْ يا  #{helpers.get_username(User.find(@round_player.user_id).email)}".play('ar')
      end
      update_game_room  
      Turbo::StreamsChannel.broadcast_replace_to(
        [@game, :started], 
        target: "#{dom_id(@game)}_room_chooser", 
        partial: "games/room_chooser", 
        locals: {
          game: @game, 
          guess: @guess,
          sentence: @sentence, 
          round: @round,
          player: @player,
          topic: @topic,
          opened_letters: @opened_letters,
          players_money: @players_money,
        }
      )
      redirect_to @game
    end
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    # TODO: Update to include:
    # - Allow users to choose how many rounds
    @game = Game.create(game_params)
    GamesUtils.create_game_player(@game, current_user, 0)
    (0..2).each do |order|
      GamesUtils.create_game_round(@game, current_user, order)
    end
    redirect_to games_path
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    # TODO: Update to include:
    # - Rounds
    # - Players
    # - Turns
    # - Track money
    # - Add total money at end of round
    if not @round.current_player_id.present?
      @round.update(current_player_id: @game.users.first.id)
    else
      update_game_room 
    end
    
    if @round.present? and @round.over?
      next_round = @round.next
      
      if next_round.present?
        @game.update(current_round_id: next_round.id)
        update_game_room
      else
        redirect_to games_url
      end
    elsif @guess.present?
      if @sentence.include? @guess and not @opened_letters.include? @guess
        @round_player.update(player_money: @round_player.player_money + @sentence.count(@guess))
        @round.update(opened_letters: @opened_letters << @guess)  
      else
        next_player = @game.next_player(@player)
        @round.update(current_player_id: next_player.id)
      end

      if @sentence.chars.uniq.sort == @round.opened_letters.sort
        @round.update(over: true)
      end
      update_game_room          
    end
    redirect_to @game    
  end

  # PATCH /games/1
  def start
    @game.update( started: true, 
                  current_round_id: @game.rounds.first.id)
    redirect_to @game
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.rounds.each do |round|
      round.round_players.delete_all
    end
    @game.rounds.delete_all
    @game.game_players.delete_all
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
      session[:current_user_id] = current_user.id
    end

    def set_game_room
      if @game.started?
        @round = Round.find(@game.current_round_id)
        @player = User.find(@round.current_player_id)
        @round_player = @round.round_players.where(user_id: @player.id).first
        @sentence = @round.sentence
        @topic = @round.topic
        @guess = params[:guess]
        @full_guess = params[:full_guess]
        @spin_result = params[:spin_result].to_i
        @opened_letters = @round.opened_letters
        @players_money = @round.round_players.map{ |round_player| "#{ helpers.get_username(User.find(round_player.user_id).email)}: #{ number_to_currency(round_player.player_money, precision: 0) }" }
      end
    end

    def update_game_room
      @round = Round.find(@game.current_round_id)

app/helpers/games_helper.rb
module GamesHelper
  def get_username(email)
    email.partition('@').first.titleize
  end
end

app/views/games/_disk.html.erb
<div id="chart"></div>
<div id="question">
  <h1></h1>
</div>
<script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<%= javascript_tag do %>
  function ready(callback){
      // in case the document is already rendered
      if (document.readyState!='loading') callback();
      // modern browsers
      else if (document.addEventListener) document.addEventListener('DOMContentLoaded', callback);
      // IE <= 8
      else document.attachEvent('onreadystatechange', function(){
          if (document.readyState=='complete') callback();
      });
  }

  ready(function() {
  var padding = {top:0, right:0, bottom:0, left:0},
      w = 300 - padding.left - padding.right,
      h = 300 - padding.top  - padding.bottom,
      r = Math.min(w, h)/2,
      rotation = 0,
      oldrotation = 0,
      picked = 100000,
      color = d3.scale.category20();
      //randomNumbers = getRandomNumbers();
  var disk_content = <%= raw disk_content.to_json %>
  var data = disk_content;
  var svg = d3.select('#chart')
      .append("svg")
      .data([data])
      .attr("width",  w + padding.left + padding.right)
      .attr("height", h + padding.top + padding.bottom);
  var container = svg.append("g")
      .attr("class", "chartholder")
      .attr("transform", "translate(" + (w/2 + padding.left) + "," + (h/2 + padding.top) + ")");
  var vis = container
      .append("g");
  
  var pie = d3.layout.pie().sort(null).value(function(d){return 1;});
  // declare an arc generator function
  var arc = d3.svg.arc().outerRadius(r);
  // select paths, use arc generator to draw
  var arcs = vis.selectAll("g.slice")
      .data(pie)
      .enter()
      .append("g")
      .attr("class", "slice");
  
  arcs.append("path")
      .attr("fill", function(d, i){ return color(i); })
      .attr("d", function (d) { return arc(d); });
  // add the text
  arcs.append("text").attr("transform", function(d){
          d.innerRadius = 0;
          d.outerRadius = 130;
          d.angle = (d.startAngle + d.endAngle)/2;
          return "rotate(" + (d.angle * 180 / Math.PI - 90) + ")translate(" + (d.outerRadius -10) +")";
      })
      .attr("text-anchor", "end")
      .text( function(d, i) {
          return data[i].label;
      });
  container.on("click", spin);
  function spin(d){
  
      container.on("click", null);
      //all slices have been seen, all done
      var  ps       = 360/data.length,
           pieslice = Math.round(1440/data.length),
           rng      = Math.floor((Math.random() * 1440) + 720);
  
      rotation = (Math.round(rng / ps) * ps);
  
      picked = Math.round(data.length - (rotation % 360)/ps);
      picked = picked >= data.length ? (picked % data.length) : picked;
      rotation += 90 - Math.round(ps/2);
      vis.transition()
          .duration(3000)
          .attrTween("transform", rotTween)
          .each("end", function(){
              //populate question
              oldrotation = rotation;
  
              container.on("click", spin);
          });
      setTimeout(function(){document.getElementById("spin_result").setAttribute("value", data[picked].question);}, 3000);
      setTimeout(function(){document.getElementById("spin_result_dead").setAttribute("value", data[picked].question);}, 3000);
      setTimeout(function(){if (document.getElementById("spin_result_dead").value == "-1"){
        document.getElementById("guess_button").click();
      }},3001)
      setTimeout(function(){
        document.getElementById("guess_field").placeholder = "احزر";
        document.getElementById("guess_field").removeAttribute("disabled");
      },3001)
  }
  //make arrow
  svg.append("g")
      .attr("transform", "translate(" + (w + padding.left + padding.right) + "," + ((h/2)+padding.top) + ")")
      .append("path")
      .attr("d", "M-" + (r*.15) + ",0L0," + (r*.05) + "L0,-" + (r*.05) + "Z")
      .style({"fill":"black"});
  //draw spin circle
  container.append("circle")
      .attr("cx", 0)
      .attr("cy", 0)
      .attr("r", 50)
      .style({"fill":"green","cursor":"pointer"});
  //spin text
  container.append("text")
      .attr("x", 0)
      .attr("y", 15)
      .attr("text-anchor", "middle")
      .text("دور")
      .style({"font-weight":"bold", "font-size":"30px"});
  
  
  function rotTween(to) {
    var i = d3.interpolate(oldrotation % 360, rotation);
    return function(t) {
      return "rotate(" + i(t) + ")";
    };
  }
  
  
  function getRandomNumbers(){
      var array = new Uint16Array(1000);
      var scale = d3.scale.linear().range([360, 1440]).domain([0, 100000]);
      if(window.hasOwnProperty("crypto") && typeof window.crypto.getRandomValues === "function"){
          window.crypto.getRandomValues(array);
          console.log("works");
      } else {
          //no support for crypto, get crappy random numbers
          for(var i=0; i < 1000; i++){
              array[i] = Math.floor(Math.random() * 100000) + 1;
          }
      }
      return array;
  }
  });
<% end %>
<style type="text/css">
  text{
      font-family:Helvetica, Arial, sans-serif;
      font-size:15px;
      pointer-events:none;
      text-shadow: 2px 2px;
      font-weight: bold;
  }
  #chart{
      position:relative;
      width:300px;
      height:300px;
      margin:auto;
  }
</style>

app/views/games/_form.html.erb
<%= form_with(model: @game, id: dom_id(@game)) do |form| -%>
  <% if @game.errors.any? %>
    <% @game.errors.full_messages.each do |message| %>
      <div class="mt-5 mb-2 mx-5 p-2 bg-danger text-light rounded-pill shadow" role="alert">
        <%= message %>
      </div>
    <% end %>
  <% end %>
  <ul class="list-group list-group-flush">
  </ul>
  <div class="d-grid mx-5">
    <%= button_tag class: "btn btn-primary modern-btn shadow-sm" do %>
      Create Game <i class="bi bi-plus-circle-fill"></i>
    <% end %>
  </div>
<% end %>

app/views/games/_game.html.erb
<%= turbo_frame_tag dom_id(game) do %>
  <div class="card modern-card-sm bg-white" style="display:inline-block;">
    <div class="row">
      <div class="col-9">
      </div>
      <div class="col-2">
        <%= button_to " X ", game, method: :delete, class: "btn btn-sm btn-danger rounded-pill mb-2 display-sm"%>
      </div>
    </div>
    <div class="card-body bg-light rounded" style="width:15rem;">
      <h5 class="">
        <%= link_to "Game #{game.id}", game, 'data-turbo-frame': :_top %>
      </h5>
      <p class="card-text"><%= time_ago_in_words game.created_at %> ago</p>
    </div>
    <div class="card-footer border-0 bg-white p-3">
      <div class="row justify-content-center">
        <%= link_to "Join", game, method: :get, 'data-turbo-frame': :_top, class: "btn btn-warning modern-btn"%>
      </div>
    </div>
  </div>
<% end %>

app/views/games/_game_room.html.erb
<button class="mb-3 btn btn-danger btn-sm modern-btn" onClick="window.location.reload();">اعد التحميل <i class="bi bi-arrow-repeat"></i> </button>
<div class="row d-flex justify-content-center text-center">
  <h1><%= (round.order + 1).ordinalize %> Round</h1>
  <h2><%= get_username(player.email) %>'s Turn</h2>
  <div class="col-md-12 d-none d-sm-none d-md-none d-lg-block d-xl-block">
    <hr>
    <div class = 'display-4 rounded text-dark'>
      <%= topic %>
    </div>
    <div dir='rtl' class = 'm-3 centered'>
      <% sentence.split.each do |word| %>
        <% word.split('').each do |letter| %>
          <%= render partial: "games/puzzle_letter", locals: {letter: letter, opened_letters: opened_letters} %>
        <% end %>
        <br>
      <% end %>
    </div>
    <hr>
  </div>
  <div>
    <%= form_with url: guess_game_path(game.id), method: :post do |form| %>
      <%= form.hidden_field :spin_result, id: "spin_result_dead", readonly: true %>
      <%= button_tag style: "display:none;", id:"guess_button" do %>
      <% end %>
    <% end %>
    <%= form_with url: guess_game_path(game.id), method: :post, class: "form-horizontal d-lg-none d-xl-none d-xl-block" do |form| %>
      <div class="row justify-content-center m-3" dir="rtl">
        <div class="col-sm-4">
          <%= form.hidden_field :spin_result, id: "spin_result", readonly: true %>
          <%= form.text_field :guess, id: "guess_field", maxlength: 1, placeholder: "دور اولا", class: "form-control rounded-pill border-0 bg-light text-center mb-3", required: true, disabled: true %>
        </div>
        <div class="col-sm-5">
          <%= button_tag class: "btn btn-primary modern-btn-sm col" do %>
            احزر حرف
          <% end %>
        </div>
      </div>
    <% end %>
    <%= form_with url: guess_game_path(game.id), method: :post, class: "form-horizontal d-lg-none d-xl-none d-xl-block" do |form| %>
      <div class="row justify-content-center m-3" dir="rtl">
        <div class="col-sm-7">
          <%= form.text_field :full_guess, placeholder: "ادخل الجملة", class: "form-control rounded-pill border-0 bg-light text-center mb-3", required: true %>
        </div>
        <div class="col-sm-5">
          <%= button_tag class: "btn btn-secondary modern-btn-sm col" do %>
            احزر الجملة
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4  d-none d-sm-none d-md-none d-lg-block d-xl-block" dir="ltr">
    <div class = "h5">فلوس اللاعبين:
      <% players_money.each do |player_money| %>
        <h4><i class="bi-caret-right-fill"></i> <%= player_money %> </h4>
      <% end %>
    </div>
  </div>
</div>

app/views/games/_puzzle_letter.html.erb
<% if opened_letters.include? letter %>
  <div class = "display-6 p-3 m-1 text-center rounded-circle bg-primary text-light b-0 shadow-sm" style = "width: 5rem; height: 5rem; display: inline-block;">
    <%= letter %>
  </div>
<% else %>
  <div class = "display-6 p-3 m-1 text-center rounded-circle bg-secondary text-secondary b-0 shadow-sm" style = "width: 5rem; height: 5rem; display: inline-block;">
    &nbsp;
  </div>
<% end %>

app/views/games/_room_chooser.html.erb
<%= turbo_stream_from game, :started %>
<%= tag.div id: "#{dom_id(game)}_room_chooser" do %>
  <% if game.started? %>
    <%= render partial: "games/game_room", locals: {
      game: game, 
      disk_content: @disk_content,
      sentence: sentence, 
      round: round,
      player: player,
      topic: topic,
      opened_letters: opened_letters,
      players_money: players_money,
    } %>
  <% else %>
    <%= render "games/waiting_room" %>
  <% end %>
<% end %>

app/views/games/_waiting_room.html.erb
<%= turbo_stream_from @game, :game_players %>
<h2 class="text-center">Hello, <%= @user %>!</h2>
<div class="rounded bg-light p-3 my-3">
  <p>This is game <%= @game.id %> with the following players:</p>
  <ul>
    <%= tag.div id: "#{dom_id(@game)}_game_players" do %>
      <%= render @game.game_players %>
    <% end %>
  </ul>
  <div class="input-group rounded border-0 bg-primary text-white">
    <%= tag.i class:"bi bi-share-fill py-2 px-3" %>
    <%= text_field_tag :link, url_for(only_path: false), readonly: true, onclick: 'this.select();', class:"form-control bg-white border-0 text-primary" %>
  </div>
</div>
<div class="submit-field d-grid gap-1 justify-content-center">
  <%= button_to start_game_path(@game), method: :patch, class: "btn btn-primary modern-btn" do %>
    Start Game <i class="bi bi-joystick"></i>
  <% end %>
</div>

app/views/games/deprecated_show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Games", games_path %></li>
  <li class="breadcrumb-item active mr-auto"><%= @game.id %></li>
</ol>
<div class="card">
  <ul class="list-group list-group-flush">
  </ul>
  <div class = 'm-3 centered'>
    <% @sentence.split.each do |word| %>
      <% word.split('').each do |letter| %>
        <%= render partial: 'puzzle_letter', locals: {letter: letter, opened_letters: @opened_letters} %>
      <% end %>
      <br>
    <% end %>
  </div>
  <%= form_with url: @game, method: :get do |form| %>
    <%= form.label :guess, "Your guess:" %>
    <%= form.text_field :guess, maxlength: 1 %>
    <%= form.submit "Submit" %>
  <% end %>
  <%= @total %>
</div>

app/views/games/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Games", games_path %></li>
  <li class="breadcrumb-item"><%= link_to @game.id, @game %></li>
  <li class="breadcrumb-item active">Edit</li>
</ol>
<%= render 'form', game: @game %>

app/views/games/index.html.erb
<ol class="m-4 breadcrumb">
  <li class="breadcrumb-item active mr-auto text-secondary">Games</li>
</ol>
<%= turbo_stream_from 'games' %>
<%= turbo_frame_tag 'game_form' do %>
  <%= render partial: 'form' %>
<% end %>
<div class="card-group d-flex flex-wrap">
  <%= turbo_frame_tag 'games' do %>
    <%= render @games %>
  <% end %>
</div>

app/views/games/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Games", games_path %></li>
  <li class="breadcrumb-item active">Add</li>
</ol>
<%= render 'form', game: @game %>

app/views/games/show.html.erb
<ol class="m-2 breadcrumb d-lg-none d-xl-none d-xl-block">
  <li class="breadcrumb-item"><%= link_to "Games", games_path, class: "text-secondary" %></li>
  <li class="breadcrumb-item text-primary"><%= @game.id %></li>
</ol>
<% if @game.started? and not @game.game_players.map(&:user_id).include? current_user.id%>
  <div class="mt-5 mb-2 mx-5 p-2 text-center bg-danger text-light rounded-pill shadow" role="alert">
    Sorry, you can only watch. The game has already started.
  </div>
<% end %>
<div class="row m-5 justify-content-center d-lg-none d-xl-none d-xl-block" dir="ltr" style="width:60%">
  <%= render partial: 'games/disk', locals: {disk_content: @disk_content} %>
</div>
<div class="card modern-card">
  <%= render partial: "room_chooser", locals: {
    game: @game, 
    disk_content: @disk_content,
    sentence: @sentence, 
    round: @round,
    player: @player,
    topic: @topic,
    opened_letters: @opened_letters,
    players_money: @players_money,
  } %>
</div>