config/routes.rb
Rails.application.routes.draw do
  get 'home_page/show'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :games do
    member do 
      patch :start
      post :guess
    end
  end
  

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root to: 'home_page#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeepPocketsDisk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>
  <body class="bg-light h-100">
      <nav class="navbar shadow-sm navbar-expand-lg navbar-dark bg-secondary mb-2">
        <div class="container-fluid">
          <%= link_to "Home", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <% if signed_in? %>
                  <%= button_to 'Sign out', sign_out_path, class: "btn bg-secondary", method: :delete %>
                <% else %>
                  <%= button_to 'Sign in', sign_in_path, class: "btn bg-secondary", method: :get %>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to 'Games', games_path, class: "btn bg-secondary", method: :get %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="mt-5 mb-2 mx-5" id="flash">
      <% flash.each do |key, value| %>
        <div class="bg-danger text-light rounded-pill shadow flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>